sistema_inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', include('dashboard.urls')),

    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path

from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('perfil/alumno/cursos', curso_alumno, name='perfil_alumno_cursos'),
    path('perfil/alumno/', perfil_alumno, name='perfil_alumno'),
    path('perfil/alumno/cursos/detalle/<int:pk>/', curso_detalle_alumno, name='curso_detalle_alumno'),

]

website/urls.py
from django.urls import path

from .views import *

from django.views.generic import TemplateView

app_name = 'website'

urlpatterns = [
    path('', index_website, name='index'),
    path('detalle-curso/<int:pk>/', detalle_curso, name='detalle_curso'),
    path('registro/', registro_alumno, name='registro_alumno'),
    path('pre-inscripcion/<int:pk>/', inscripcion_alumno, name='inscripcion_curso'),
    path('quienes-somos/', TemplateView.as_view(template_name='website/quienes_somos.html'), name='quienes_somos'),
    path('contacto/', contacto_website, name='contacto'),
    # path('inscripcion', TemplateView.as_view(template_name='website/inscripcion_curso.html'), name='inscripcion_curso'),
]

cursos/models.py
from django.contrib.auth.models import User
from django.db import models


class Curso(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=250)
    descripcion = models.TextField(blank=True)
    categoria = models.ForeignKey('CategoriaCurso', on_delete=models.CASCADE)

    class Meta:
        db_table = 'curso'
        ordering = ['titulo']

    def __str__(self):
        return self.titulo


class CursoOfertado(models.Model):
    sedes = (
        (1, 'Plantel Centro'),
        (2, 'Plantel Tenosique'),
    )

    instructor = models.CharField(max_length=250)
    precio = models.DecimalField(max_digits=8, decimal_places=2)  # 999999.99
    fecha_inicio = models.DateField(blank=True, null=True)
    sede = models.PositiveSmallIntegerField(choices=sedes)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    capacidad = models.PositiveSmallIntegerField(default=15)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    estatus = models.ForeignKey('EstatusCursoOfertado', on_delete=models.CASCADE)

    class Meta:
        db_table = 'curso_ofertado'

    def __str__(self):
        return f'{self.curso.titulo} - {self.estatus.nombre}'


class EstatusCursoOfertado(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = 'estatus_curso_ofertado'

    def __str__(self):
        return self.nombre


class CategoriaCurso(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = 'categoria_curso'

    def __str__(self):
        return self.nombre


class EstatusPreinscripcionCurso(models.Model):
    nombre = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'estatus_preinscripcion_curso'

    def __str__(self):
        return self.nombre


class PreinscripcionCurso(models.Model):
    curso = models.ForeignKey(CursoOfertado, on_delete=models.CASCADE)
    prospecto = models.ForeignKey(User, on_delete=models.CASCADE)
    comprobante_domicilio = models.FileField(upload_to='archivos_inscripcion')
    curp = models.FileField(upload_to='archivos_inscripcion')
    identifacion_oficial = models.FileField(upload_to='archivos_inscripcion')
    comprobante_pago = models.FileField(upload_to='archivos_inscripcion', blank=True, null=True)
    comprobante_estudio = models.FileField(upload_to='archivos_inscripcion')
    acta_nacimiento = models.FileField(upload_to='archivos_inscripcion')
    estatus = models.ForeignKey(EstatusPreinscripcionCurso, on_delete=models.CASCADE)
    nota = models.CharField(max_length=250, blank=True)
    fecha_solicitud = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'preinscripcion_curso'

    def __str__(self):
        return f'{self.prospecto.first_name} - {self.curso.curso.titulo}'

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms

from cursos.models import PreinscripcionCurso, CategoriaCurso


class InscripcionAlumnoCursoForm(forms.Form):
    comprobante_domicilio = forms.FileField()
    curp = forms.FileField()
    identificacion_oficial = forms.FileField()
    comprobante_pago = forms.FileField()
    comprobante_estudios = forms.FileField()
    acta_nacimiento = forms.FileField()


class PreinscripcionAlumnoCursoModelForm(forms.ModelForm):
    class Meta:
        model = PreinscripcionCurso
        fields = [
            'comprobante_domicilio',
            'curp',
            'identifacion_oficial',
            'comprobante_pago',
            'comprobante_estudio',
            'acta_nacimiento',
        ]


class BusquedaCursoForm(forms.Form):
    nombre_curso = forms.CharField(required=False, widget=forms.TextInput(attrs={'name':'search',}))
    categorias = forms.ModelChoiceField(queryset=CategoriaCurso.objects.all(), required=False)

website/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.core.mail import send_mail

from cursos.models import CursoOfertado, EstatusPreinscripcionCurso, PreinscripcionCurso
from website.forms import InscripcionAlumnoCursoForm, PreinscripcionAlumnoCursoModelForm, BusquedaCursoForm
from django.contrib import messages


def index_website(request):
    form = BusquedaCursoForm()

    curso_ofertado_lista = CursoOfertado.objects.filter(estatus_id=1)
    search = request.GET.get('search', None)
    nombre_curso = request.GET.get('nombre_curso', None)
    categoria_id = request.GET.get('categorias', None)

    if search:
        curso_ofertado_lista = curso_ofertado_lista.filter(curso__titulo__icontains=search)

    elif nombre_curso or categoria_id:

        if nombre_curso:
            curso_ofertado_lista = curso_ofertado_lista.filter(curso__titulo__icontains=nombre_curso)

        if categoria_id:
            curso_ofertado_lista = curso_ofertado_lista.filter(curso__categoria_id=categoria_id)


    context = {
        'curso_ofertado_lista': curso_ofertado_lista,
        'form': form
    }

    return render(request, 'website/index.html', context)


def detalle_curso(request, pk):
    inscrito = False
    curso_ofertado = CursoOfertado.objects.get(id=pk)
    if not request.user.is_anonymous:
        if PreinscripcionCurso.objects.filter(curso=curso_ofertado, prospecto=request.user).exists():
            inscrito = True
    # print(PreinscripcionCurso.objects.get(curso=curso_ofertado, prospecto=request.user))
    context = {'curso_ofertado': curso_ofertado, 'inscrito': inscrito}
    return render(request, 'website/detalle_curso.html', context)


def registro_alumno(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    context = {'form': form}
    return render(request, 'registration/registro_alumno.html', context)


@login_required
def inscripcion_alumno(request, pk):
    curso_ofertado = CursoOfertado.objects.get(pk=pk)
    form = PreinscripcionAlumnoCursoModelForm()
    if request.method == 'POST':
        form = PreinscripcionAlumnoCursoModelForm(request.POST, request.FILES)
        if form.is_valid():
            curso_ofertado_temp = form.save(commit=False)
            curso_ofertado_temp.prospecto = request.user
            curso_ofertado_temp.curso = curso_ofertado
            curso_ofertado_temp.estatus_id = 1
            curso_ofertado_temp.save()
            messages.success(request, 'Pre inscrito correctamente')
            return redirect('usuarios:perfil_alumno_cursos')

    context = {
        'form': form,
        'curso_ofertado': curso_ofertado
    }

    return render(request, 'website/inscripcion_curso.html', context)


class InscripcionAlumno(TemplateView):
    template_name = 'website/inscripcion_curso.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = InscripcionAlumnoCursoForm()
        context['form'] = form
        return context

def contacto_website(request):
    if request.method == 'POST':
        email = request.POST.get('email', None)
        mensaje = request.POST.get('mensaje',None)

        if email and mensaje:
            try:
                send_mail('contacto desde la web', mensaje, email, ['tavo.jmnz91@gmail.com'])
                messages.success(request, 'Correo enviado con exito')
                return redirect('website:contacto')
            except Exception as e:
                messages.error(request, 'Ocurrio un error al enviar el correo, intentelo de nuevo')

    return render(request,'website/contacto.html')

website/templates/website/base_website.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'website/navbar.html' %}
{% endblock %}

website/templates/website/contacto.html
{% extends 'website/base_website.html' %}

{% block titulo_tab %}
    Contacto
{% endblock %}

{% block contenido %}
    <div class="row">
        <div class="col">
            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}

            <h1>Contactanos</h1>
            <form action="" method="post">
                {% csrf_token %}
                <label for="">Correo electronico</label>
                <input type="email" class="form-control" name="email" required>
                <label for="">Mensaje</label>
                <textarea name="mensaje" cols="30" rows="10" class="form-control" required></textarea>
                <br>
                <input type="submit" class="btn btn-outline-primary">
            </form>
        </div>
    </div>
{% endblock %}

website/templates/website/detalle_curso.html
{% extends 'website/base_website.html' %}

{% block titulo_tab %}
    {{ curso_ofertado.curso.titulo }} - CURSOSPRO
{% endblock %}

{% block contenido %}
    <div class="row py-5">
        <div class="col">
            <h1>{{ curso_ofertado.curso.titulo }}</h1>
            <p>{{ curso_ofertado.estatus.nombre }}</p>
            <p>{{ curso_ofertado.curso.categoria.nombre }}</p>
            <img src="https://via.placeholder.com/440x260" class="card-img-top" alt="...">
            <p>{{ curso_ofertado.instructor }}</p>
            <p>${{ curso_ofertado.precio }}</p>
            <p>
                {{ curso_ofertado.curso.descripcion }}
            </p>
            {% if not inscrito %}
                <a href="{% url 'website:inscripcion_curso' curso_ofertado.pk %}" class="btn btn-primary">Pre
                    inscribirme</a>
            {% else %}
                <h3 class="text-success">Ya inscrito</h3>

            {% endif %}

        </div>
    </div>
{% endblock %}

website/templates/website/index.html
{% extends 'website/base_website.html' %}

{% block titulo_tab %}
    Incio
{% endblock %}

{% block contenido %}
    <div class="row py-5">
        <div class="col">

            <div class="card mb-2">
                <div class="card-body">
                    <form>
                        {{ form }}
                        <button type="submit" class="btn btn-sm btn-outline-primary">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </button>
                    </form>
                </div>
            </div>

            {% for curso_ofertado in curso_ofertado_lista %}
                <div class="card" style="width: 18rem;">
                    <img src="https://via.placeholder.com/640x360" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ curso_ofertado.curso.titulo }}</h5>
                        <p>{{ curso_ofertado.instructor }}</p>
                        <p>${{ curso_ofertado.precio }}</p>
                        <p>Sede: {{ curso_ofertado.get_sede_display }}</p>
                        <a href="{% url 'website:detalle_curso' curso_ofertado.id %}" class="btn btn-primary">Ver</a>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        let nombre_curso_input = document.getElementById("id_nombre_curso");
        let categoria_select = document.getElementById("id_categorias");

        nombre_curso_input.value = '{{ request.GET.nombre_curso }}';
        //nombre_curso_input.classList.add("form-control");

        categoria_select.value = '{{ request.GET.categorias }}'
        //categoria_select.classList.add("form-select");

    </script>
{% endblock %}

website/templates/website/inscripcion_curso.html
{% extends 'website/base_website.html' %}

{% block titulo_tab %}
    Preinscripcion {{ curso_ofertado.curso.titulo }} - CURSOSPRO
{% endblock %}

{% block contenido %}
    <div class="row py-5">
        <div class="col">
            <h2>Preinscripcion al curso {{ curso_ofertado.curso.titulo }}</h2>
            <p>Adjuntar los siguientes documentos para la preinscripcion</p>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2">
                            <input type="submit" class="btn btn-outline-primary" value="Preinscribirme">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

website/templates/website/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'website:index' %}">CURSOSPRO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'website:index' %}">Inicio</a>
                </li>

                {#                <li class="nav-item dropdown">#}
                {#                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"#}
                {#                       aria-expanded="false">#}
                {#                        Categorias#}
                {#                    </a>#}
                {#                    <ul class="dropdown-menu">#}
                {#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
                {#                        <li><a class="dropdown-item" href="#">Another action</a></li>#}
                {#                        <li>#}
                {#                            <hr class="dropdown-divider">#}
                {#                        </li>#}
                {#                        <li><a class="dropdown-item" href="#">Something else here</a></li>#}
                {#                    </ul>#}
                {#                </li>#}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'website:quienes_somos' %}">Quienes somos</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'website:contacto' %}">Contacto</a>
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'usuarios:perfil_alumno' %}">Mi perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Salir</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'login' %}">Iniciar sesion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'website:registro_alumno' %}">
                            Registrarse
                        </a>
                    </li>
                {% endif %}


            </ul>
            {% if request.user.is_authenticated %}
                <span class="navbar-text mx-2">
                    {{ request.user }}
            </span>
            {% endif %}

            {% if request.path == '/' %}
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Buscar cursos..." aria-label="Search"
                           name="search" value="{{ request.GET.search }}">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
            {% endif %}

        </div>
    </div>
</nav>

website/templates/website/quienes_somos.html
{% extends 'website/base_website.html' %}

{% block titulo_tab %}
    Quiene somos
{% endblock %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h1>Quienes somos</h1>
            <img src="http://placeimg.com/640/360/any" alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus in iure numquam rem temporibus vero
                voluptatum! Aperiam architecto aspernatur, commodi cumque esse explicabo ipsa nulla quisquam similique
                suscipit, tempora, vitae!
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus in iure numquam rem temporibus vero
                voluptatum! Aperiam architecto aspernatur, commodi cumque esse explicabo ipsa nulla quisquam similique
                suscipit, tempora, vitae!
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus in iure numquam rem temporibus vero
                voluptatum! Aperiam architecto aspernatur, commodi cumque esse explicabo ipsa nulla quisquam similique
                suscipit, tempora, vitae!
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem commodi,
                ducimus eius eos error est excepturi necessitatibus nisi nobis officia pariatur provident quidem
                recusandae repellendus sunt vitae?</p>
        </div>
    </div>
{% endblock %}