dashboard/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', index_dashboard,name='index'),
    path('lista-curso/', lista_curso, name='lista_curso'),
    path('preinscripciones/', preinscripciones, name='preinscripciones'),
    path('preinscripcion/<int:pk>', preinscripcion_editar, name='preinscripcion_editar'),
]

sistema_inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', include('dashboard.urls')),

    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from .views import *

from django.views.generic import TemplateView

app_name = 'website'

urlpatterns = [
    path('', index_website, name='index'),
    path('detalle-curso/<int:pk>/', detalle_curso, name='detalle_curso'),
    path('registro/', registro_alumno, name='registro_alumno'),
    path('pre-inscripcion/<int:pk>/', inscripcion_alumno, name='inscripcion_curso'),
    path('quienes-somos/', TemplateView.as_view(template_name='website/quienes_somos.html'), name='quienes_somos'),
    path('contacto/', contacto_website, name='contacto'),
    # path('inscripcion', TemplateView.as_view(template_name='website/inscripcion_curso.html'), name='inscripcion_curso'),
]

cursos/models.py
from django.contrib.auth.models import User
from django.db import models


class Curso(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=250)
    descripcion = models.TextField(blank=True)
    categoria = models.ForeignKey('CategoriaCurso', on_delete=models.CASCADE)

    class Meta:
        db_table = 'curso'
        ordering = ['titulo']

    def __str__(self):
        return self.titulo


class CursoOfertado(models.Model):
    sedes = (
        (1, 'Plantel Centro'),
        (2, 'Plantel Tenosique'),
    )

    instructor = models.CharField(max_length=250)
    precio = models.DecimalField(max_digits=8, decimal_places=2)  # 999999.99
    fecha_inicio = models.DateField(blank=True, null=True)
    sede = models.PositiveSmallIntegerField(choices=sedes)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    capacidad = models.PositiveSmallIntegerField(default=15)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    estatus = models.ForeignKey('EstatusCursoOfertado', on_delete=models.CASCADE)

    class Meta:
        db_table = 'curso_ofertado'

    def __str__(self):
        return f'{self.curso.titulo} - {self.estatus.nombre}'


class EstatusCursoOfertado(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = 'estatus_curso_ofertado'

    def __str__(self):
        return self.nombre


class CategoriaCurso(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = 'categoria_curso'

    def __str__(self):
        return self.nombre


class EstatusPreinscripcionCurso(models.Model):
    nombre = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'estatus_preinscripcion_curso'

    def __str__(self):
        return self.nombre


class PreinscripcionCurso(models.Model):
    curso = models.ForeignKey(CursoOfertado, on_delete=models.CASCADE)
    prospecto = models.ForeignKey(User, on_delete=models.CASCADE)
    comprobante_domicilio = models.FileField(upload_to='archivos_inscripcion')
    curp = models.FileField(upload_to='archivos_inscripcion')
    identifacion_oficial = models.FileField(upload_to='archivos_inscripcion')
    comprobante_pago = models.FileField(upload_to='archivos_inscripcion', blank=True, null=True)
    comprobante_estudio = models.FileField(upload_to='archivos_inscripcion')
    acta_nacimiento = models.FileField(upload_to='archivos_inscripcion')
    estatus = models.ForeignKey(EstatusPreinscripcionCurso, on_delete=models.CASCADE)
    nota = models.CharField(max_length=250, blank=True)
    fecha_solicitud = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'preinscripcion_curso'

    def __str__(self):
        return f'{self.prospecto.first_name} - {self.curso.curso.titulo}'

dashboard/models.py
from django.db import models

# Create your models here.

cursos/forms.py
from django import forms

from cursos.models import PreinscripcionCurso


class PreinscripcionCursoModelForm(forms.ModelForm):
    class Meta:
        model = PreinscripcionCurso
        exclude = ['curso', 'prospecto', 'estatus']

dashboard/forms.py
from django import forms

from cursos.models import PreinscripcionCurso


class PreinscripcionDashboardModelForm(forms.ModelForm):
    class Meta:
        model = PreinscripcionCurso
        fields = ['estatus', 'nota']

cursos/views.py
from django.shortcuts import render

# Create your views here.

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from cursos.models import PreinscripcionCurso, CursoOfertado
from dashboard.forms import PreinscripcionDashboardModelForm


@login_required
def index_dashboard(request):
    if not request.user.groups.filter(name='administracion').exists():
        return redirect('website:index')

    return render(request, 'dashboard/index.html')


@login_required
def lista_curso(request):
    cursos_ofertados = CursoOfertado.objects.all()
    context = {
        'cursos_ofertados': cursos_ofertados
    }

    return render(request, 'dashboard/cursos/lista_curso.html', context)


@login_required
def preinscripciones(request):
    preinscripciones_lista = PreinscripcionCurso.objects.all()

    context = {
        'preinscripciones_lista': preinscripciones_lista,
    }
    return render(request, 'dashboard/cursos/preinscripciones.html', context)


@login_required
def preinscripcion_editar(request, pk):
    preinscripcion = PreinscripcionCurso.objects.get(pk=pk)
    form = PreinscripcionDashboardModelForm(instance=preinscripcion)
    if request.method == 'POST':
        form = PreinscripcionDashboardModelForm(request.POST, instance=preinscripcion)
        if form.is_valid():
            form.save()
            return redirect('dashboard:preinscripciones')

    context = {
        'preinscripcion': preinscripcion,
        'form': form,
    }
    return render(request, 'dashboard/cursos/preinscripciones_editar.html', context)

dashboard/templates/dashboard/cursos/lista_curso.html
{% extends 'dashboard/base_dashboard.html' %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h1>Cursos ofertados</h1>
            {% if perms.cursos.add_cursoofertado %}
                <a href="#">Nuevo curso</a>
            {% endif %}
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Curso</th>
                    <th>Estatus</th>
                    <th>Opciones</th>
                </tr>
                </thead>
                <tbody>
                {% for cursos_ofertado in cursos_ofertados %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cursos_ofertado.curso.titulo }}</td>
                        <td>{{ cursos_ofertado.estatus }}</td>
                        <td>
                            {% if perms.cursos.change_cursoofertado %}
                                <a href="#">Editar</a>
                            {% endif %}
                            {% if perms.cursos.delete_cursoofertado %}
                                <a href="#">Borrar</a>
                            {% endif %}


                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

dashboard/templates/dashboard/cursos/preinscripciones.html
{% extends 'dashboard/base_dashboard.html' %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h1>Preinscripciones</h1>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Curso</th>
                    <th>Prospecto</th>
                    <th>Estatus</th>
                    <th>Opciones</th>
                </tr>
                </thead>
                <tbody>
                {% for preinscripcion in preinscripciones_lista %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ preinscripcion.curso.curso.titulo }}</td>
                        <td>{{ preinscripcion.prospecto.first_name }}</td>
                        <td>{{ preinscripcion.estatus }}</td>
                        <td>
                            <a href="{% url 'dashboard:preinscripcion_editar' preinscripcion.pk %}">Editar</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

dashboard/templates/dashboard/cursos/preinscripciones_editar.html
{% extends 'dashboard/base_dashboard.html' %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h1>Preinscripcion - editar</h1>
            <p>Curso: {{ preinscripcion.curso.curso.titulo }}</p>
            <p>Prospecto: {{ preinscripcion.prospecto.first_name }}</p>
            <p>Comprobante de domiclio: <a href="{{ preinscripcion.comprobante_domicilio.url }}" target="_blank">Ver</a>
            </p>
            <p>CURP: <a href="{{ preinscripcion.curp.url }}" target="_blank">Ver</a></p>
            <p>Identificacion oficial: <a href="{{ preinscripcion.identifacion_oficial.url }}" target="_blank">Ver</a>
            </p>
            <p>Comprobante de pago: <a href="{{ preinscripcion.comprobante_pago.url }}" target="_blank">Ver</a></p>
            <p>Acta de nacimiento: <a href="{{ preinscripcion.acta_nacimiento.url }}" target="_blank">Ver</a></p>
            <p>Fecha de solicitud: {{ preinscripcion.fecha_solicitud }}</p>

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table table-hover">
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2">
                            <input type="submit" class="btn btn-outline-primary" value="Guardar">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>


{% endblock %}