dashboard/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', index_dashboard,name='index'),
    path('lista-curso/', lista_curso, name='lista_curso'),
    path('preinscripciones/', preinscripciones, name='preinscripciones'),
    path('preinscripcion/<int:pk>', preinscripcion_editar, name='preinscripcion_editar'),
]

sistema_inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', include('dashboard.urls')),

    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from .views import *

from django.views.generic import TemplateView

app_name = 'website'

urlpatterns = [
    path('', index_website, name='index'),
    path('detalle-curso/<int:pk>/', detalle_curso, name='detalle_curso'),
    path('registro/', registro_alumno, name='registro_alumno'),
    path('pre-inscripcion/<int:pk>/', inscripcion_alumno, name='inscripcion_curso'),
    path('quienes-somos/', TemplateView.as_view(template_name='website/quienes_somos.html'), name='quienes_somos'),
    path('contacto/', contacto_website, name='contacto'),
    # path('inscripcion', TemplateView.as_view(template_name='website/inscripcion_curso.html'), name='inscripcion_curso'),
]

cursos/models.py
from django.contrib.auth.models import User
from django.db import models


class Curso(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=250)
    descripcion = models.TextField(blank=True)
    categoria = models.ForeignKey('CategoriaCurso', on_delete=models.CASCADE)

    class Meta:
        db_table = 'curso'
        ordering = ['titulo']

    def __str__(self):
        return self.titulo


class CursoOfertado(models.Model):
    sedes = (
        (1, 'Plantel Centro'),
        (2, 'Plantel Tenosique'),
    )

    instructor = models.CharField(max_length=250)
    precio = models.DecimalField(max_digits=8, decimal_places=2)  # 999999.99
    fecha_inicio = models.DateField(blank=True, null=True)
    sede = models.PositiveSmallIntegerField(choices=sedes)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    capacidad = models.PositiveSmallIntegerField(default=15)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    estatus = models.ForeignKey('EstatusCursoOfertado', on_delete=models.CASCADE)

    class Meta:
        db_table = 'curso_ofertado'

    def __str__(self):
        return f'{self.curso.titulo} - {self.estatus.nombre}'


class EstatusCursoOfertado(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = 'estatus_curso_ofertado'

    def __str__(self):
        return self.nombre


class CategoriaCurso(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table = 'categoria_curso'

    def __str__(self):
        return self.nombre


class EstatusPreinscripcionCurso(models.Model):
    nombre = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'estatus_preinscripcion_curso'

    def __str__(self):
        return self.nombre


class PreinscripcionCurso(models.Model):
    curso = models.ForeignKey(CursoOfertado, on_delete=models.CASCADE)
    prospecto = models.ForeignKey(User, on_delete=models.CASCADE)
    comprobante_domicilio = models.FileField(upload_to='archivos_inscripcion')
    curp = models.FileField(upload_to='archivos_inscripcion')
    identifacion_oficial = models.FileField(upload_to='archivos_inscripcion')
    comprobante_pago = models.FileField(upload_to='archivos_inscripcion', blank=True, null=True)
    comprobante_estudio = models.FileField(upload_to='archivos_inscripcion')
    acta_nacimiento = models.FileField(upload_to='archivos_inscripcion')
    estatus = models.ForeignKey(EstatusPreinscripcionCurso, on_delete=models.CASCADE)
    nota = models.CharField(max_length=250, blank=True)
    fecha_solicitud = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'preinscripcion_curso'

    def __str__(self):
        return f'{self.prospecto.first_name} - {self.curso.curso.titulo}'

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms

from cursos.models import PreinscripcionCurso


class PreinscripcionDashboardModelForm(forms.ModelForm):
    class Meta:
        model = PreinscripcionCurso
        fields = ['estatus', 'nota']

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from cursos.models import PreinscripcionCurso, CursoOfertado
from dashboard.forms import PreinscripcionDashboardModelForm


@login_required
def index_dashboard(request):
    if not request.user.groups.filter(name='administracion').exists():
        return redirect('website:index')

    return render(request, 'dashboard/index.html')


@login_required
def lista_curso(request):
    cursos_ofertados = CursoOfertado.objects.all()
    context = {
        'cursos_ofertados': cursos_ofertados
    }

    return render(request, 'dashboard/cursos/lista_curso.html', context)


@login_required
def preinscripciones(request):
    preinscripciones_lista = PreinscripcionCurso.objects.all()

    context = {
        'preinscripciones_lista': preinscripciones_lista,
    }
    return render(request, 'dashboard/cursos/preinscripciones.html', context)


@login_required
def preinscripcion_editar(request, pk):
    preinscripcion = PreinscripcionCurso.objects.get(pk=pk)
    form = PreinscripcionDashboardModelForm(instance=preinscripcion)
    if request.method == 'POST':
        form = PreinscripcionDashboardModelForm(request.POST, instance=preinscripcion)
        if form.is_valid():
            form.save()
            return redirect('dashboard:preinscripciones')

    context = {
        'preinscripcion': preinscripcion,
        'form': form,
    }
    return render(request, 'dashboard/cursos/preinscripciones_editar.html', context)

dashboard/templates/dashboard/base_dashboard.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sitio administrativo">
    <meta name="author" content="Gustavo Jimenez">

    <title>
        {% block titulo_tab %}
            Dashboard
        {% endblock %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/dashboard/">


    <link href="{% static 'dashboard/assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard/dashboard.css' %}" rel="stylesheet">

    {% block extra_css %}

    {% endblock %}
</head>
<body>

{% include 'dashboard/navbar.html' %}

<div class="container-fluid">
    <div class="row">
        {% include 'dashboard/sidebar.html' %}

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            {% block contenido %}

            {% endblock %}
        </main>
    </div>
</div>

<script src="{% static 'dashboard/assets/dist/js/bootstrap.bundle.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
        crossorigin="anonymous"></script>
<script src="{% static 'dashboard/dashboard.js' %}"></script>

{% block extra_js %}

{% endblock %}

</body>
</html>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base_dashboard.html' %}

{% block contenido %}
<h1>Index</h1>
    {{ request.user }}
{% endblock %}

dashboard/templates/dashboard/navbar.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">CURSOS PRO</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Buscar"
           aria-label="Search">
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="{% url 'logout' %}">Salir</a>
        </div>
    </div>
</header>

dashboard/templates/dashboard/sidebar.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">
                    <span data-feather="home" class="align-text-bottom"></span>
                    Inicio
                </a>
            </li>
            {% if perms.cursos.view_cursoofertado %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:lista_curso' %}">
                        <span data-feather="file" class="align-text-bottom"></span>
                        Cursos
                    </a>
                </li>
            {% endif %}


            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:preinscripciones' %}">
                    <span data-feather="file" class="align-text-bottom"></span>
                    Preinscripciones
                </a>
            </li>

        </ul>

        {% comment %}
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
            <span>Saved reports</span>
            <a class="link-secondary" href="#" aria-label="Add a new report">
                <span data-feather="plus-circle" class="align-text-bottom"></span>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text" class="align-text-bottom"></span>
                    Current month
                </a>
            </li>
        </ul>
        {% endcomment %}
    </div>
</nav>