sistema_inscripciones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('dashboard/', include('dashboard.urls')),

    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path

from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('perfil/alumno/cursos', curso_alumno, name='perfil_alumno_cursos'),
    path('perfil/alumno/', perfil_alumno, name='perfil_alumno'),
    path('perfil/alumno/cursos/detalle/<int:pk>/', curso_detalle_alumno, name='curso_detalle_alumno'),

]

website/urls.py
from django.urls import path

from .views import *

from django.views.generic import TemplateView

app_name = 'website'

urlpatterns = [
    path('', index_website, name='index'),
    path('detalle-curso/<int:pk>/', detalle_curso, name='detalle_curso'),
    path('registro/', registro_alumno, name='registro_alumno'),
    path('pre-inscripcion/<int:pk>/', inscripcion_alumno, name='inscripcion_curso'),
    path('quienes-somos/', TemplateView.as_view(template_name='website/quienes_somos.html'), name='quienes_somos'),
    path('contacto/', contacto_website, name='contacto'),
    # path('inscripcion', TemplateView.as_view(template_name='website/inscripcion_curso.html'), name='inscripcion_curso'),
]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

usuarios/views.py
from django.shortcuts import render, redirect

from cursos.models import PreinscripcionCurso
from cursos.forms import PreinscripcionCursoModelForm
from usuarios.forms import UserModelForm
from django.contrib import messages


def perfil_alumno(request):
    form = UserModelForm(instance=request.user)
    if request.method == 'POST':
        form = UserModelForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Perfil actualizado correctamente')
            return redirect('usuarios:perfil_alumno')

    context = {
        'form': form,
    }
    return render(request, 'usuarios/perfil_aulmno.html', context)


def curso_alumno(request):
    cursos = PreinscripcionCurso.objects.filter(prospecto=request.user)
    context = {
        'cursos': cursos
    }
    return render(request, 'usuarios/cursos_alumno.html', context)


def curso_detalle_alumno(request, pk):
    curso = PreinscripcionCurso.objects.get(pk=pk)
    form = PreinscripcionCursoModelForm(instance=curso)

    if request.method == 'POST':
        form = PreinscripcionCursoModelForm(request.POST, request.FILES, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('usuarios:perfil_alumno_cursos')
        else:
            print(form.errors)

    context = {
        'curso': curso,
        'form': form
    }
    return render(request, 'usuarios/curso_detalle_alumno.html', context)

usuarios/templates/usuarios/curso_detalle_alumno.html
{% extends 'website/base_website.html' %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h3>Detalle del curso: {{ curso.curso.curso.titulo }}</h3>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table table-hover">
                    {{ form.as_table }}
                    {% if curso.estatus.nombre != 'Aceptado' %}
                        <tr>
                            <td>
                                <input type="submit" value="Actualizar">
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </form>

        </div>
    </div>
{% endblock %}

usuarios/templates/usuarios/cursos_alumno.html
{% extends 'website/base_website.html' %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h3>Mis cursos</h3>

            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}

            <table class="table">
                <thead>
                <tr>
                    <th>Curso</th>
                    <th>Estatus</th>
                </tr>
                </thead>
                <tbody>
                {% for curso in cursos %}
                    <tr>
                        <td>
                            <a href="{% url 'usuarios:curso_detalle_alumno' curso.pk %}">
                                {{ curso }}
                            </a>
                        </td>
                        <td>{{ curso.estatus }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

usuarios/templates/usuarios/perfil_aulmno.html
{% extends 'website/base_website.html' %}

{% block titulo_tab %}
    Mi perfil
{% endblock %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h1>Mi perfil </h1>

            {% if messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}

            <form action="" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <td>
                            <input type="submit" class="btn btn-outline-primary" value="Actualizar">
                        </td>
                    </tr>
                </table>
            </form>
            <a href="{% url 'change_password' %}">Cambiar contraseña</a>
        </div>
    </div>
    <hr>
    <div class="row mt-5">
        <div class="col">
            <ul>
                <li><a href="{% url 'usuarios:perfil_alumno_cursos' %}">Mis cursos</a></li>
            </ul>
        </div>
    </div>
{% endblock %}